### ISSUE TITLE
Determine what portion of SOUL tokens to grant to start auctions. Need some token engineering help.

### ISSUE THREAD

**Issue by simondlr** [artonomous/artonomous-mvp#26]
I think this is potentially where we can get some help from token engineering simulations.

For each generator, it donates some SOUL tokens that is staked to that generator to whomever starts each auction.

The goal of this is two-fold:

- Get people to start auctions (same as birthing fee for cryptokitties).
- Add some friction to kickstarting generators and keeping them alive. I think the overall value proposition of artonomous increases if generators can effectively "die" if they are not popular (the art they are generating is not that great). This latter component can be so extreme that it essentially limits the amount of generators quite a lot. eg, the long tail of generators won't really survive. But it should probably find some middle ground. What portion to donate each time is hard to determine. Can be a fixed percentage, or and adjust percentage. What that is, is still hard to figure out.

**Comment by markusbkoch** [comment]
I like what you said in #21 
>I feel it's important to design this in such a way that there's no magic numbers involved: eg choosing a hardcoded fee or choosing a hardcoded percentage threshold. These are unknown at this stage, so would rather opt for some more continuous, market-based options.

How about having callers compete for the fee in a reverse auction?

**Comment by markusbkoch** [comment]
IMO, though, incentivizing callers is not as needed in Artonomous as it is in CryptoKitties. It's in the generators best interest to start auctions within the 256 blocks period. As long as the system does not make it impossible for them to delegate this task to others, people will come up with different incentivization strategies, both on- and off-chain.

**Comment by simondlr** [comment]
> It's in the generators best interest to start auctions within the 256 blocks period.

I'm not 100% sure what you are referring to here? The blockhash is chosen at the start of the auction itself, so the blockhash limit shouldn't be an issue?

And yes, it seems like the incentive should be enough to start it since it's in the interest of generator creators to kickstart it.

**Comment by markusbkoch** [comment]
As the start-auction transaction is being processed, the hash of the block
it will be included in is unknown. The hash of the previous block could be
used, but then people would know the hash (and thus the art piece) before
they start the auction, and could decide on whether or not to start it
based on that information.

So an interesting design for extracting randomness from block hashes is to
use the hash of a "future block". In cryptokitties, the breeding
transaction defines the future block (breeding block + cooldown period).
From the point of view of the birthing transaction, that is a block in the
past, so its hash is available (for 256 blocks).

Different implementations could achieve the same result in artonomous, such
as one auction defining the block of the next, or having two separate
transactions to start an auction (something like schedule+start). Clearly
defining and simulating them would allow one to prove and/or estimate how
well they meet the requirements and what impact they have on other parts of
the system.





Em seg, 2 de jul de 2018 16:33, Simon de la Rouviere <
notifications@github.com> escreveu:

**Comment by markusbkoch** [comment]
By the way, this is a good post on the subject
https://blog.positive.com/predicting-random-numbers-in-ethereum-smart-contracts-e5358c6b8620

Em seg, 2 de jul de 2018 16:33, Simon de la Rouviere <
notifications@github.com> escreveu:

**Comment by simondlr** [comment]
> As the start-auction transaction is being processed, the hash of the block it will be included in is unknown.

Oh, derp. Of course. Yes.

> The hash of the previous block could be used, but then people would know the hash (and thus the art piece) before they start the auction, and could decide on whether or not to start it based on that information.

I don't initially this is a problem since ultimately it is about letting the generator produce good art, so it will be optimized towards choosing/starting on whomever believes it is good.

A future blockhash doesn't make sense to me, since you need to be able to see the artwork if you want to decide to buy it.

cc @nickreynolds. This is relevant to the discussion in #20.

**Comment by simondlr** [comment]
Closing for now. Opting to not include a carrot-on-the-stick to kickstart an auction. :)
