### ISSUE TITLE
Hacking on Artonomous @ EthBerlin

### ISSUE THREAD

**Issue by tarrencev** [artonomous/artonomous-mvp#40]
Hey all,

I think it would be awesome to get a team together to hack on Artonomous at EthBerlin.

If anyone else is interested, drop a message below and we can use this issue to coordinate!

**Comment by sethfork** [comment]
Sounds awesome! I could be down

**Comment by EdsonAlcala** [comment]
me too !

**Comment by BenCmjn** [comment]
Hi there,
I just stumble upon this for team building.
https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding
Hope it helps! ;)

**Comment by tarrencev** [comment]
Hey guys, thanks for the responses! I've cross posted to https://github.com/ethberlin-hackathon/ETHBerlin-Teambuilding/issues/19. Lets keep the discussion going there!

**Comment by simondlr** [comment]
Exciting! Let me know if there's anything I can help with in prepping for ETHBerlin.

**Comment by gmcmullen** [comment]
Hey gang! @simondlr told me I should hook up with you guys for ETHBerlin. What do you have planned? I'm a lawyer so I won't bring coding expertise, but I'm a co-author of [COALA IP](https://github.com/COALAIP/specs) and know my way around blockchain+law. 

@TimDaub — what do you say?

**Comment by TimDaub** [comment]
Hi,


I'd be interested in helping here. I can do backend and frontend. I don't know much about Solidity programming yet, but I might be teaching myself some in the next few days. Also contributed to COALA IP.

**Comment by bdflex** [comment]
Amazing project. I saw you need some UX help. I'm working with our UX guy to do some work on this. We won't be able to make it over to Berlin but if we can get you some screens mocked up would that be useful? What are the rules for the hackathon? Are you allowed prep in advance? I'll get an initial draft over by Friday 31st giving us a week to get feedback and update.

**Comment by tarrencev** [comment]
Hey all, thanks for the responses! Excited to hack on this with you all.

Lets plan on meeting during team formation at 11pm Friday.

@bdflex I'm not sure exactly the rules of the hackathon, we'll have to chat with the organizers to figure out if we can use any existing work or need to redo some. That said, I think some UX ideas would be awesome and a great contribution to the project!

**Comment by bdflex** [comment]
@tarrencev @simondlr Here is what we have so far. It's just a suggestion - so we'd love to get feedback on.

https://drive.google.com/drive/folders/12-fTYYx1KliQKYoTnKAOx1rwcmHYqK6d?usp=sharing

**Comment by bdflex** [comment]
@tarrencev @simondlr Here is what we have so far:
https://drive.google.com/drive/folders/1zGPFOzwIhifdZBVegq3UpoJmUM5HfmfI?usp=sharing

Just a suggestion. We'd love to get feedback and rework it.

**Comment by simondlr** [comment]
> I'm not sure exactly the rules of the hackathon, we'll have to chat with the organizers to figure out if we can use any existing work or need to redo some.

Let me know.

Regardless. Go crazy in whatever way.

@tarrencev I made you an admin of the repo, so feel free to commit/write/whatever you want during the hackathon. I don't want to be a blocker during that weekend, so take the reins as you guys wish!

**Comment by simondlr** [comment]
@bdflex that's a pretty great start! Think that would be helpful to work from. This, along with @djosey's proposals in this thread is good enough to get an MVP going sufficiently, I feel. 

https://github.com/artonomous/artonomous-mvp/issues/24 :)

Exciting!

**Comment by tarrencev** [comment]
Hey all, really excited to hack tonight! I think maybe the easiest way to coordinate is to meet at the team formation event this evening. Looking forward to meeting you all!

**Comment by BenCmjn** [comment]
Update your today's position ;)
Also, do not hesitate to use the [EthBerlin mentor's ticket system](https://ethberlin-helpq.herokuapp.com)
Looking forward to meet you guys!

**Comment by tarrencev** [comment]
Closing this out! Thanks everyone!

**Comment by ebaizel** [comment]
@tarrencev @bdflex how far did you guys get on this?  was any work merged back into the main repo?  also, if you've got any suggestions on what to pick up next that'd be great.  thanks!

**Comment by tarrencev** [comment]
@ebaizel we got a mvp up and running, you can find more info here: https://github.com/artonomous/ethberlin/

**Comment by ebaizel** [comment]
@tarrencev the mvp looks really slick!  are there plans to merge it into the artonomous-mvp project or are you just going to keep it separate?  i'd love to keep adding to it.  looks like i'm getting a contract related error on the home page which is preventing it from loading anything, which i can look into.  thx
