### ISSUE TITLE
Front-End Framework Requirements

### ISSUE THREAD

**Issue by simondlr** [artonomous/artonomous-mvp#5]
- Preferably in Redux.
- Should be responsive and work in mobile browsers such as Status or Toshi.
- Work completely client-side. No reliance on other components.

**Comment by nickreynolds** [comment]
https://github.com/simondlr/artonomous/pull/28

I setup this pull request to integrate drizzle into the front-end. I was mostly just trying to learn about Drizzle by trying it out, so no harm if you want to close it without merging and go with a different solution. I think for a relatively simple DApp, it might be the way to go (but I'm no expert).

**Comment by simondlr** [comment]
Closing for now. I think for now we have a good base to work from.
